"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Estudiante_js_1 = require("./Estudiante.js");
var Profesor_js_1 = require("./Profesor.js");
var PersonalServicio_js_1 = require("./PersonalServicio.js");
var estudiante = new Estudiante_js_1.Estudiante("Mia", "Loreto", "123456", "Soltera", "3er Año");
var profesor = new Profesor_js_1.Profesor("Lucas", "Alvarez", "789012", "Casado", 2015, 101, "Lenguajes");
var personal = new PersonalServicio_js_1.PersonalServicio("Carla", "Perez", "345678", "Soltera", 2018, 202, "Biblioteca");
console.log("\n--- Información Inicial ---");
estudiante.imprimirInfo();
profesor.imprimirInfo();
personal.imprimirInfo();
console.log("\n--- Actualizaciones ---");
estudiante.matricularNuevoCurso("4to Año");
profesor.cambiarDepartamento("Arquitectura");
personal.trasladarSeccion("Secretaría");
console.log("\n--- Información Actualizada ---");
estudiante.imprimirInfo();
profesor.imprimirInfo();
personal.imprimirInfo();
